#!/usr/bin/env node
// Lay out capdag, tagged-urn and lungo-ts for a browser: the ES modules as
// they are, each beside the WebAssembly program it instantiates, with the
// package names they import by rewritten to the paths they are laid out at —
// so a page loads them without a bundler or an import map.
//
//   <outDir>/lungo-ts/        the WebAssembly host every generated program runs on
//   <outDir>/tagged-urn/      tagged-urn.js and its model (formal/)
//   <outDir>/capdag/          capdag.js, cap-fab-renderer.js and their model (formal/)
//   <outDir>/capdag/browser.js
//
// browser.js puts the public names of tagged-urn, capdag and the renderer on
// the page's global object, for page scripts that are not modules
// (capdag-dot-com, macfloom's web views). The programs are instantiated when
// the modules are first imported, so a page imports browser.js from a module
// script of its own and uses the globals after that import.
//
// Running: `node build-browser.js [outDir]`. Default outDir is ./dist.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = process.argv[2] ? path.resolve(process.argv[2]) : path.join(here, 'dist');

/** The directory of a package this one imports, as Node resolves it from here. */
function packageDir(name, entry) {
  const dir = path.dirname(fileURLToPath(import.meta.resolve(name)));
  if (!fs.existsSync(path.join(dir, entry))) {
    throw new Error(`${name} resolved to ${dir}, which has no ${entry}`);
  }
  return dir;
}

/**
 * Copy `files` from `from` to `to`, replacing in each the import specifiers
 * `rewrites` names for it. Every rewrite must apply: a source that no longer
 * imports what this expects would otherwise ship still naming a package the
 * browser cannot resolve.
 */
function lay(from, to, files, rewrites = {}) {
  for (const file of files) {
    const source = path.join(from, file);
    const target = path.join(to, file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    const replacing = rewrites[file];
    if (!replacing) {
      fs.copyFileSync(source, target);
      continue;
    }
    let text = fs.readFileSync(source, 'utf8');
    for (const [specifier, replacement] of Object.entries(replacing)) {
      const forms = [`from '${specifier}'`, `from "${specifier}"`];
      const found = forms.filter((form) => text.includes(form));
      if (found.length === 0) {
        throw new Error(`${source} does not import '${specifier}', which the browser layout rewrites`);
      }
      for (const form of found) {
        text = text.split(form).join(`from '${replacement}'`);
      }
    }
    fs.writeFileSync(target, text);
  }
  console.log(`  laid out ${to}`);
}

const taggedUrnDir = packageDir('tagged-urn', 'tagged-urn.js');
const lungoTsDir = packageDir('lungo-ts', 'index.js');
const parser = path.join(here, 'machine-parser.js');
if (!fs.existsSync(parser)) {
  throw new Error(`machine-parser.js not found at ${parser} — run 'npm run build:parser' first`);
}

for (const dir of ['lungo-ts', 'tagged-urn', 'capdag']) {
  fs.rmSync(path.join(outDir, dir), { recursive: true, force: true });
}

const model = { 'formal/index.js': { 'lungo-ts': '../../lungo-ts/index.js' } };

lay(lungoTsDir, path.join(outDir, 'lungo-ts'), ['index.js', 'wasi.js']);
lay(taggedUrnDir, path.join(outDir, 'tagged-urn'),
  ['tagged-urn.js', 'formal/index.js', 'formal/program.wasm'], model);
lay(here, path.join(outDir, 'capdag'),
  ['capdag.js', 'planner.js', 'machine-parser.js', 'cap-fab-renderer.js', 'formal/index.js', 'formal/program.wasm'],
  { ...model, 'capdag.js': { 'tagged-urn': '../tagged-urn/tagged-urn.js' } });

fs.writeFileSync(path.join(outDir, 'capdag', 'browser.js'), `// Generated by capdag-js/build-browser.js. Do not edit.
//
// The public names of tagged-urn, capdag and the renderer, on the page's
// global object. Import this from a module script; the names are there once
// the import has completed.

import * as taggedUrn from '../tagged-urn/tagged-urn.js';
import * as capdag from './capdag.js';
import { CapFabRenderer } from './cap-fab-renderer.js';

// Both packages export an ErrorCodes; each is published under its own name.
const { ErrorCodes: TaggedUrnErrorCodes, ...taggedUrnNames } = taggedUrn;
const { ErrorCodes: CapUrnErrorCodes, ...capdagNames } = capdag;

Object.assign(globalThis, taggedUrnNames, capdagNames, {
  TaggedUrnErrorCodes,
  CapUrnErrorCodes,
  CapFabRenderer,
});
`);
console.log(`browser modules written to ${outDir}`);
