// Generated by lungo 1.78.3254 from Lean 4.34.1 for program capdagFormal. Do not edit.
import * as L from "lungo-ts";

async function programModule() {
  const url = new URL("./program.wasm", import.meta.url);
  if (typeof process !== "undefined" && process.versions?.node) {
    const { readFile } = await import("node:fs/promises");
    return readFile(url);
  }
  const response = await fetch(url);
  if (!response.ok) throw new Error(`cannot load ${url}: ${response.status}`);
  return response.arrayBuffer();
}

/** Describes CapDAG.Exec.WfCap for polymorphic functions. */
export function wfCapType() {
  return new L.Type(
    L.inductiveExpr(0),
    (w, v) => {
      if (typeof v !== "object" || v === null) throw new L.MalformedError("not a CapDAG.Exec.WfCap");
      w.u32(0);
      wfType().encode(w, v.input);
      wfType().encode(w, v.output);
      wfType().encode(w, v.other);
      effectType().encode(w, v.effect);
    },
    (r) => {
      const c = r.u32();
      if (c !== 0) throw new L.MalformedError(`constructor index ${c} of CapDAG.Exec.WfCap`);
      return ({ input: wfType().decode(r), output: wfType().decode(r), other: wfType().decode(r), effect: effectType().decode(r) });
    },
  );
}

/** Describes CapDAG.Effect for polymorphic functions. */
export function effectType() {
  return new L.Type(
    L.inductiveExpr(1),
    (w, v) => {
      if (typeof v !== "object" || v === null) throw new L.MalformedError("not a CapDAG.Effect");
      switch (v.kind) {
        case "unspecified":
          w.u32(0);
          return;
        case "declared":
          w.u32(1);
          return;
        case "none":
          w.u32(2);
          return;
        case "patch":
          w.u32(3);
          return;
        default:
          throw new L.MalformedError(`${String(v.kind)} is not a constructor of CapDAG.Effect`);
      }
    },
    (r) => {
      const c = r.u32();
      switch (c) {
        case 0: return ({ kind: "unspecified" });
        case 1: return ({ kind: "declared" });
        case 2: return ({ kind: "none" });
        case 3: return ({ kind: "patch" });
        default: throw new L.MalformedError(`constructor index ${c} of CapDAG.Effect`);
      }
    },
  );
}

/** Describes CapDAG.Exec.WfQuery for polymorphic functions. */
export function wfQueryType() {
  return new L.Type(
    L.inductiveExpr(2),
    (w, v) => {
      if (typeof v !== "object" || v === null) throw new L.MalformedError("not a CapDAG.Exec.WfQuery");
      w.u32(0);
      wfAskType().encode(w, v.input);
      wfAskType().encode(w, v.output);
      wfType().encode(w, v.tags);
      effectType().encode(w, v.effect);
    },
    (r) => {
      const c = r.u32();
      if (c !== 0) throw new L.MalformedError(`constructor index ${c} of CapDAG.Exec.WfQuery`);
      return ({ input: wfAskType().decode(r), output: wfAskType().decode(r), tags: wfType().decode(r), effect: effectType().decode(r) });
    },
  );
}

/** Lean's TaggedUrn.Exec.Wf, held by handle: only the program's functions make and read its values. */
export class Wf extends L.Opaque {}

/** Describes TaggedUrn.Exec.Wf for polymorphic functions. */
export function wfType() {
  return new L.Type(
    L.inductiveExpr(3),
    (w, v) => {
      if (!(v instanceof Wf)) throw new L.MalformedError("not a TaggedUrn.Exec.Wf");
      L.OPAQUE.encode(w, v);
    },
    (r) => new Wf(r.program, r.u64()),
  );
}

/** Describes CapDAG.Grade for polymorphic functions. */
export function gradeType() {
  return new L.Type(
    L.inductiveExpr(4),
    (w, v) => {
      if (typeof v !== "object" || v === null) throw new L.MalformedError("not a CapDAG.Grade");
      switch (v.kind) {
        case "exact":
          w.u32(0);
          return;
        case "guaranteed":
          w.u32(1);
          return;
        case "possible":
          w.u32(2);
          return;
        case "none":
          w.u32(3);
          return;
        default:
          throw new L.MalformedError(`${String(v.kind)} is not a constructor of CapDAG.Grade`);
      }
    },
    (r) => {
      const c = r.u32();
      switch (c) {
        case 0: return ({ kind: "exact" });
        case 1: return ({ kind: "guaranteed" });
        case 2: return ({ kind: "possible" });
        case 3: return ({ kind: "none" });
        default: throw new L.MalformedError(`constructor index ${c} of CapDAG.Grade`);
      }
    },
  );
}

/** Describes TaggedUrn.Constraint for polymorphic functions. */
export function constraintType() {
  return new L.Type(
    L.inductiveExpr(5),
    (w, v) => {
      if (typeof v !== "object" || v === null) throw new L.MalformedError("not a TaggedUrn.Constraint");
      switch (v.kind) {
        case "missing":
          w.u32(0);
          return;
        case "unconstrained":
          w.u32(1);
          return;
        case "optionalNot":
          w.u32(2);
          L.STRING.encode(w, v.value);
          return;
        case "present":
          w.u32(3);
          return;
        case "presentNot":
          w.u32(4);
          L.STRING.encode(w, v.value);
          return;
        case "exact":
          w.u32(5);
          L.STRING.encode(w, v.value);
          return;
        case "absent":
          w.u32(6);
          return;
        default:
          throw new L.MalformedError(`${String(v.kind)} is not a constructor of TaggedUrn.Constraint`);
      }
    },
    (r) => {
      const c = r.u32();
      switch (c) {
        case 0: return ({ kind: "missing" });
        case 1: return ({ kind: "unconstrained" });
        case 2: return ({ kind: "optionalNot", value: L.STRING.decode(r) });
        case 3: return ({ kind: "present" });
        case 4: return ({ kind: "presentNot", value: L.STRING.decode(r) });
        case 5: return ({ kind: "exact", value: L.STRING.decode(r) });
        case 6: return ({ kind: "absent" });
        default: throw new L.MalformedError(`constructor index ${c} of TaggedUrn.Constraint`);
      }
    },
  );
}

/** Describes CapDAG.Exec.WfAsk for polymorphic functions. */
export function wfAskType() {
  return new L.Type(
    L.inductiveExpr(6),
    (w, v) => {
      if (typeof v !== "object" || v === null) throw new L.MalformedError("not a CapDAG.Exec.WfAsk");
      switch (v.kind) {
        case "unknown":
          w.u32(0);
          return;
        case "within":
          w.u32(1);
          wfType().encode(w, v.u);
          return;
        case "covers":
          w.u32(2);
          wfType().encode(w, v.u);
          return;
        case "same":
          w.u32(3);
          wfType().encode(w, v.u);
          return;
        default:
          throw new L.MalformedError(`${String(v.kind)} is not a constructor of CapDAG.Exec.WfAsk`);
      }
    },
    (r) => {
      const c = r.u32();
      switch (c) {
        case 0: return ({ kind: "unknown" });
        case 1: return ({ kind: "within", u: wfType().decode(r) });
        case 2: return ({ kind: "covers", u: wfType().decode(r) });
        case 3: return ({ kind: "same", u: wfType().decode(r) });
        default: throw new L.MalformedError(`constructor index ${c} of CapDAG.Exec.WfAsk`);
      }
    },
  );
}

/** The layout fingerprint and descriptor of each type, by Lean name, for modules using them. */
export const leanTypes = Object.freeze({
  "CapDAG.Exec.WfCap": Object.freeze({ fingerprint: "2b8d6466d218f4ae6bc98d95bba55d98f21cac4a49446ae170993773cefdb830", type: wfCapType }),
  "CapDAG.Effect": Object.freeze({ fingerprint: "38c7bd3c0527cda156713cd441c9b6b92bd5df8a39108fa101449a789abcb477", type: effectType }),
  "CapDAG.Exec.WfQuery": Object.freeze({ fingerprint: "e734861d70e3177f6563c4492990bb65131f0450b8dfc62071eb61b6c5f08b8e", type: wfQueryType }),
  "TaggedUrn.Exec.Wf": Object.freeze({ fingerprint: "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785", type: wfType }),
  "CapDAG.Grade": Object.freeze({ fingerprint: "0a2a20a14d9ecca6121343df2d8a7f2478b3e837710ed522ed385d35efdf46f2", type: gradeType }),
  "TaggedUrn.Constraint": Object.freeze({ fingerprint: "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7", type: constraintType }),
  "CapDAG.Exec.WfAsk": Object.freeze({ fingerprint: "d286477c7abc4e6bc6ee2d06889372b71a5bb06605b592ebabb6ad3eaf71b952", type: wfAskType }),
});

/** The Lean program capdagFormal. */
export class CapdagFormal {
  #program;
  constructor(program) {
    this.#program = program;
  }
  accepts(pattern, cap) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_daccepts", [], [[wfCapType(), pattern], [wfCapType(), cap]], L.value(L.BOOL));
  }
  comparable(a, b) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dcomparable", [], [[wfCapType(), a], [wfCapType(), b]], L.value(L.BOOL));
  }
  dispatch(candidate, request) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_ddispatch", [], [[wfCapType(), candidate], [wfCapType(), request]], L.value(L.BOOL));
  }
  effectOk(candidate, request) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_deffectOk", [], [[effectType(), candidate], [effectType(), request]], L.value(L.BOOL));
  }
  equivalent(a, b) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dequivalent", [], [[wfCapType(), a], [wfCapType(), b]], L.value(L.BOOL));
  }
  flows(a, b) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dflows", [], [[wfCapType(), a], [wfCapType(), b]], L.value(L.BOOL));
  }
  mayDispatch(candidate, request) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dmayDispatch", [], [[wfCapType(), candidate], [wfCapType(), request]], L.value(L.BOOL));
  }
  mayFlow(a, b) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dmayFlow", [], [[wfCapType(), a], [wfCapType(), b]], L.value(L.BOOL));
  }
  queryAdmits(q, c) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryAdmits", [], [[wfQueryType(), q], [wfCapType(), c]], L.value(L.BOOL));
  }
  queryBetween(input, output, tags) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryBetween", [], [[wfType(), input], [wfType(), output], [wfType(), tags]], L.value(wfQueryType()));
  }
  queryConsuming(input, tags) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryConsuming", [], [[wfType(), input], [wfType(), tags]], L.value(wfQueryType()));
  }
  queryGrade(q, c) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryGrade", [], [[wfQueryType(), q], [wfCapType(), c]], L.value(gradeType()));
  }
  queryMayAdmit(q, c) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryMayAdmit", [], [[wfQueryType(), q], [wfCapType(), c]], L.value(L.BOOL));
  }
  queryOfPattern(p) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryOfPattern", [], [[wfCapType(), p]], L.value(wfQueryType()));
  }
  queryOfRequest(r_) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryOfRequest", [], [[wfCapType(), r_]], L.value(wfQueryType()));
  }
  queryProducing(output, tags) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dqueryProducing", [], [[wfType(), output], [wfType(), tags]], L.value(wfQueryType()));
  }
  rankingKey(candidate, request) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_drankingKey", [], [[wfCapType(), candidate], [wfCapType(), request]], L.value(L.pair(L.NAT, L.NAT)));
  }
  select(candidates, request) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dselect", [], [[L.list(wfCapType()), candidates], [wfCapType(), request]], L.value(L.option(wfCapType())));
  }
  specificity(c) {
    return this.#program.invoke("capdagFormal__call_l_CapDAG_dExec_dspecificity", [], [[wfCapType(), c]], L.value(L.NAT));
  }
  make(scheme, tags) {
    return this.#program.invoke("capdagFormal__call_l_TaggedUrn_dExec_dmake", [], [[L.STRING, scheme], [L.list(L.pair(L.STRING, constraintType())), tags]], L.value(L.option(wfType())));
  }
}

/** Instantiates the program; `options.host` implements its externs. */
export async function load(options = {}) {
  const program = await L.Program.load(options.module ?? (await programModule()), { wasi: options.wasi });
  program.types("capdagFormal__types");
  return new CapdagFormal(program);
}
