// Generated by lungo 1.84.11 from Lean 4.34.1 for program capdagFormal. Do not edit.
import * as L from "lungo-ts";

/** Lean's CapDAG.Bifaci.Credit.Gate. */
export interface Gate {
  readonly available: bigint;
  readonly closed: L.Option<string>;
}
export function gateType(): L.Type<Gate>;

/** Lean's CapDAG.Bifaci.Credit.Acquire. */
export type Acquire =
  | { readonly kind: "acquired"; readonly gate: Gate }
  | { readonly kind: "wait" }
  | { readonly kind: "closed"; readonly reason: string }
;
export function acquireType(): L.Type<Acquire>;

/** Lean's CapDAG.Bifaci.Credit.Window. */
export interface Window {
  readonly remaining: bigint;
  readonly pending: bigint;
  readonly batch: bigint;
}
export function windowType(): L.Type<Window>;

/** Lean's CapDAG.Bifaci.Credit.Arrival. */
export type CreditArrival =
  | { readonly kind: "accepted"; readonly window: Window }
  | { readonly kind: "violation" }
;
export function creditArrivalType(): L.Type<CreditArrival>;

/** Lean's CapDAG.Bifaci.Credit.Granted. */
export interface Granted {
  readonly window: Window;
  readonly grant: bigint;
}
export function grantedType(): L.Type<Granted>;

/** Lean's CapDAG.Bifaci.Flow.FrameType. */
export type FrameType =
  | { readonly kind: "hello" }
  | { readonly kind: "req" }
  | { readonly kind: "chunk" }
  | { readonly kind: "fin" }
  | { readonly kind: "log" }
  | { readonly kind: "err" }
  | { readonly kind: "heartbeat" }
  | { readonly kind: "streamStart" }
  | { readonly kind: "streamEnd" }
  | { readonly kind: "relayNotify" }
  | { readonly kind: "relayState" }
  | { readonly kind: "cancel" }
  | { readonly kind: "credit" }
  | { readonly kind: "closeStream" }
;
export function frameTypeType(): L.Type<FrameType>;

/** Lean's CapDAG.Bifaci.Flow.Reorder. */
export interface Reorder {
  readonly expected: bigint;
  readonly held: Array<bigint>;
}
export function reorderType(): L.Type<Reorder>;

/** Lean's CapDAG.Bifaci.Flow.Accepted. */
export type Accepted =
  | { readonly kind: "deliver"; readonly flow: Reorder; readonly seqs: Array<bigint> }
  | { readonly kind: "hold"; readonly flow: Reorder }
  | { readonly kind: "stale" }
  | { readonly kind: "duplicate" }
  | { readonly kind: "overflow" }
;
export function acceptedType(): L.Type<Accepted>;

/** Lean's CapDAG.Bifaci.Pools.State. */
export interface State {
  readonly pools: Array<Pool>;
  readonly queue: Array<Waiter>;
  readonly next: bigint;
}
export function stateType(): L.Type<State>;

/** Lean's CapDAG.Bifaci.Pools.Waiter. */
export interface Waiter {
  readonly ticket: bigint;
  readonly chain: Array<string>;
}
export function waiterType(): L.Type<Waiter>;

/** Lean's CapDAG.Bifaci.Pools.Arrival. */
export type PoolsArrival =
  | { readonly kind: "admitted"; readonly state: State }
  | { readonly kind: "queued"; readonly state: State; readonly ticket: bigint; readonly position: bigint }
  | { readonly kind: "unknownPool"; readonly name: string }
;
export function poolsArrivalType(): L.Type<PoolsArrival>;

/** Lean's CapDAG.Bifaci.Pools.Patience. */
export type Patience =
  | { readonly kind: "unbounded" }
  | { readonly kind: "atMost"; readonly remaining: bigint }
  | { readonly kind: "exhausted" }
;
export function patienceType(): L.Type<Patience>;

/** Lean's CapDAG.Bifaci.Request.Phase. */
export type Phase =
  | { readonly kind: "created" }
  | { readonly kind: "streaming" }
;
export function phaseType(): L.Type<Phase>;

/** Lean's CapDAG.Bifaci.Request.Emitted. */
export type Emitted =
  | { readonly kind: "streamStart"; readonly stream: string }
  | { readonly kind: "chunk"; readonly stream: string; readonly index: bigint }
  | { readonly kind: "streamEnd"; readonly stream: string; readonly count: L.Option<bigint> }
  | { readonly kind: "fin" }
  | { readonly kind: "err" }
  | { readonly kind: "other" }
;
export function emittedType(): L.Type<Emitted>;

/** Lean's CapDAG.Bifaci.Request.Violation. */
export type Violation =
  | { readonly kind: "afterEnd" }
  | { readonly kind: "streamRestarted"; readonly stream: string }
  | { readonly kind: "streamNotOpen"; readonly stream: string }
  | { readonly kind: "chunkOutOfPlace"; readonly stream: string; readonly expected: bigint; readonly got: bigint }
  | { readonly kind: "chunkCountWrong"; readonly stream: string; readonly sent: bigint; readonly said: bigint }
  | { readonly kind: "endWithOpenStream"; readonly stream: string }
;
export function violationType(): L.Type<Violation>;

/** Lean's CapDAG.Bifaci.Request.Disposition. */
export type Disposition =
  | { readonly kind: "route" }
  | { readonly kind: "straggler" }
  | { readonly kind: "noRoute" }
;
export function dispositionType(): L.Type<Disposition>;

/** Lean's CapDAG.Bifaci.Request.Terminal. */
export type Terminal =
  | { readonly kind: "finished" }
  | { readonly kind: "failed" }
  | { readonly kind: "cancelled" }
  | { readonly kind: "masterDied" }
;
export function terminalType(): L.Type<Terminal>;

/** Lean's CapDAG.Bifaci.Request.Write. */
export type Write =
  | { readonly kind: "send"; readonly ends: boolean }
  | { readonly kind: "suppress" }
;
export function writeType(): L.Type<Write>;

/** Lean's CapDAG.Exec.WfCap. */
export interface WfCap {
  readonly input: Wf;
  readonly output: Wf;
  readonly other: Wf;
  readonly effect: Effect;
}
export function wfCapType(): L.Type<WfCap>;

/** Lean's CapDAG.Effect. */
export type Effect =
  | { readonly kind: "unspecified" }
  | { readonly kind: "declared" }
  | { readonly kind: "none" }
  | { readonly kind: "patch" }
;
export function effectType(): L.Type<Effect>;

/** Lean's CapDAG.Exec.WfQuery. */
export interface WfQuery {
  readonly input: WfAsk;
  readonly output: WfAsk;
  readonly tags: Wf;
  readonly effect: Effect;
}
export function wfQueryType(): L.Type<WfQuery>;

/** Lean's TaggedUrn.Exec.Wf, held by handle: only the program's functions make and read its values. */
export class Wf extends L.Opaque {
  private constructor();
}
export function wfType(): L.Type<Wf>;

/** Lean's CapDAG.Grade. */
export type Grade =
  | { readonly kind: "exact" }
  | { readonly kind: "guaranteed" }
  | { readonly kind: "possible" }
  | { readonly kind: "none" }
;
export function gradeType(): L.Type<Grade>;

/** Lean's TaggedUrn.Constraint. */
export type Constraint =
  | { readonly kind: "missing" }
  | { readonly kind: "unconstrained" }
  | { readonly kind: "optionalNot"; readonly value: string }
  | { readonly kind: "present" }
  | { readonly kind: "presentNot"; readonly value: string }
  | { readonly kind: "exact"; readonly value: string }
  | { readonly kind: "absent" }
;
export function constraintType(): L.Type<Constraint>;

/** Lean's CapDAG.Bifaci.Pools.Pool. */
export interface Pool {
  readonly name: string;
  readonly capacity: bigint;
  readonly active: bigint;
}
export function poolType(): L.Type<Pool>;

/** Lean's CapDAG.Exec.WfAsk. */
export type WfAsk =
  | { readonly kind: "unknown" }
  | { readonly kind: "within"; readonly u: Wf }
  | { readonly kind: "covers"; readonly u: Wf }
  | { readonly kind: "same"; readonly u: Wf }
;
export function wfAskType(): L.Type<WfAsk>;

/** The layout fingerprint and descriptor of each type, by Lean name, for modules using them. */
export const leanTypes: {
  readonly [lean: string]: { readonly fingerprint: string; readonly type: (...args: L.Type<any>[]) => L.Type<any> };
};

/** The Lean program capdagFormal. */
export class CapdagFormal {
  private constructor();
  /** Lean's CapDAG.Bifaci.Credit.Gate.acquire : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Acquire */
  acquire(g: Gate, n: bigint): Acquire;
  /** Lean's CapDAG.Bifaci.Credit.Gate.close : CapDAG.Bifaci.Credit.Gate → String → CapDAG.Bifaci.Credit.Gate */
  close(g: Gate, reason: string): Gate;
  /** Lean's CapDAG.Bifaci.Credit.Gate.grant : CapDAG.Bifaci.Credit.Gate → Nat → CapDAG.Bifaci.Credit.Gate */
  grant(g: Gate, n: bigint): Gate;
  /** Lean's CapDAG.Bifaci.Credit.Gate.opened : Nat → CapDAG.Bifaci.Credit.Gate */
  gateOpened(window: bigint): Gate;
  /** Lean's CapDAG.Bifaci.Credit.Window.arrive : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Arrival */
  windowArrive(w_: Window): CreditArrival;
  /** Lean's CapDAG.Bifaci.Credit.Window.consume : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted */
  consume(w_: Window): Granted;
  /** Lean's CapDAG.Bifaci.Credit.Window.continued : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted */
  continued(w_: Window): Granted;
  /** Lean's CapDAG.Bifaci.Credit.Window.flush : CapDAG.Bifaci.Credit.Window → CapDAG.Bifaci.Credit.Granted */
  flush(w_: Window): Granted;
  /** Lean's CapDAG.Bifaci.Credit.Window.opened : Nat → CapDAG.Bifaci.Credit.Window */
  windowOpened(window: bigint): Window;
  /** Lean's CapDAG.Bifaci.Credit.grantTarget : List (Option String) → Option String → Option (Option String) */
  grantTarget(streams: Array<L.Option<string>>, named: L.Option<string>): L.Option<L.Option<string>>;
  /** Lean's CapDAG.Bifaci.Credit.negotiate : Nat → Nat → Option Nat */
  negotiate(ours: bigint, theirs: bigint): L.Option<bigint>;
  /** Lean's CapDAG.Bifaci.Flow.FrameType.code : CapDAG.Bifaci.Flow.FrameType → Nat */
  code(a: FrameType): bigint;
  /** Lean's CapDAG.Bifaci.Flow.FrameType.isFlow : CapDAG.Bifaci.Flow.FrameType → Bool */
  isFlow(a: FrameType): boolean;
  /** Lean's CapDAG.Bifaci.Flow.FrameType.isTerminal : CapDAG.Bifaci.Flow.FrameType → Bool */
  isTerminal(a: FrameType): boolean;
  /** Lean's CapDAG.Bifaci.Flow.FrameType.ofCode : Nat → Option CapDAG.Bifaci.Flow.FrameType */
  ofCode(a: bigint): L.Option<FrameType>;
  /** Lean's CapDAG.Bifaci.Flow.Reorder.accept : CapDAG.Bifaci.Flow.Reorder → Nat → Nat → CapDAG.Bifaci.Flow.Accepted */
  accept(r_: Reorder, seq: bigint, limit: bigint): Accepted;
  /** Lean's CapDAG.Bifaci.Flow.Reorder.start : CapDAG.Bifaci.Flow.Reorder */
  start(): Reorder;
  /** Lean's CapDAG.Bifaci.Pools.State.admit : CapDAG.Bifaci.Pools.State → Nat → Option CapDAG.Bifaci.Pools.State */
  admit(s: State, ticket: bigint): L.Option<State>;
  /** Lean's CapDAG.Bifaci.Pools.State.admitNext : CapDAG.Bifaci.Pools.State → Option (CapDAG.Bifaci.Pools.Waiter × CapDAG.Bifaci.Pools.State) */
  admitNext(s: State): L.Option<[Waiter, State]>;
  /** Lean's CapDAG.Bifaci.Pools.State.arrive : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival */
  stateArrive(s: State, chain: Array<string>): PoolsArrival;
  /** Lean's CapDAG.Bifaci.Pools.State.empty : CapDAG.Bifaci.Pools.State */
  empty(): State;
  /** Lean's CapDAG.Bifaci.Pools.State.hasRoom : CapDAG.Bifaci.Pools.State → List String → Bool */
  hasRoom(s: State, chain: Array<string>): boolean;
  /** Lean's CapDAG.Bifaci.Pools.State.heldBack : CapDAG.Bifaci.Pools.State → String → Nat */
  heldBack(s: State, name: string): bigint;
  /** Lean's CapDAG.Bifaci.Pools.State.join : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.Arrival */
  join(s: State, chain: Array<string>): PoolsArrival;
  /** Lean's CapDAG.Bifaci.Pools.State.leave : CapDAG.Bifaci.Pools.State → Nat → CapDAG.Bifaci.Pools.State */
  leave(s: State, ticket: bigint): State;
  /** Lean's CapDAG.Bifaci.Pools.State.position : CapDAG.Bifaci.Pools.State → Nat → Nat */
  position(s: State, ticket: bigint): bigint;
  /** Lean's CapDAG.Bifaci.Pools.State.release : CapDAG.Bifaci.Pools.State → List String → CapDAG.Bifaci.Pools.State */
  release(s: State, chain: Array<string>): State;
  /** Lean's CapDAG.Bifaci.Pools.State.setCapacity : CapDAG.Bifaci.Pools.State → String → Nat → CapDAG.Bifaci.Pools.State */
  setCapacity(s: State, name: string, capacity: bigint): State;
  /** Lean's CapDAG.Bifaci.Pools.advertised : Bool → String → Nat → Option Nat → Nat */
  advertised(running: boolean, pool: string, configured: bigint, available: L.Option<bigint>): bigint;
  /** Lean's CapDAG.Bifaci.Pools.chain : String → List (String × List String) → List String */
  chain(cap: string, shared: Array<[string, Array<string>]>): Array<string>;
  /** Lean's CapDAG.Bifaci.Pools.effective : Nat → Option Nat → Nat */
  effective(configured: bigint, available: L.Option<bigint>): bigint;
  /** Lean's CapDAG.Bifaci.Pools.patience : Option Nat → Nat → CapDAG.Bifaci.Pools.Patience */
  patience(unavailableFor: L.Option<bigint>, grace: bigint): Patience;
  /** Lean's CapDAG.Bifaci.Request.Phase.after : CapDAG.Bifaci.Request.Phase → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Phase */
  after(p: Phase, frame: FrameType): Phase;
  /** Lean's CapDAG.Bifaci.Request.check : List CapDAG.Bifaci.Request.Emitted → Option CapDAG.Bifaci.Request.Violation */
  check(frames: Array<Emitted>): L.Option<Violation>;
  /** Lean's CapDAG.Bifaci.Request.dispose : Bool → Bool → CapDAG.Bifaci.Request.Disposition */
  dispose(live: boolean, endedLately: boolean): Disposition;
  /** Lean's CapDAG.Bifaci.Request.ledger : Int → CapDAG.Bifaci.Flow.FrameType → Nat → Int */
  ledger(remaining: bigint, frame: FrameType, granted: bigint): bigint;
  /** Lean's CapDAG.Bifaci.Request.terminalOf : CapDAG.Bifaci.Flow.FrameType → Option CapDAG.Bifaci.Request.Terminal */
  terminalOf(a: FrameType): L.Option<Terminal>;
  /** Lean's CapDAG.Bifaci.Request.write : Bool → CapDAG.Bifaci.Flow.FrameType → CapDAG.Bifaci.Request.Write */
  write(over: boolean, frame: FrameType): Write;
  /** Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  accepts(pattern: WfCap, cap: WfCap): boolean;
  /** Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  comparable(a: WfCap, b: WfCap): boolean;
  /** Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  dispatch(candidate: WfCap, request: WfCap): boolean;
  /** Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool */
  effectOk(candidate: Effect, request: Effect): boolean;
  /** Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  equivalent(a: WfCap, b: WfCap): boolean;
  /** Lean's CapDAG.Exec.flows : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  flows(a: WfCap, b: WfCap): boolean;
  /** Lean's CapDAG.Exec.mayDispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  mayDispatch(candidate: WfCap, request: WfCap): boolean;
  /** Lean's CapDAG.Exec.mayFlow : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  mayFlow(a: WfCap, b: WfCap): boolean;
  /** Lean's CapDAG.Exec.queryAdmits : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool */
  queryAdmits(q: WfQuery, c: WfCap): boolean;
  /** Lean's CapDAG.Exec.queryBetween : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
  queryBetween(input: Wf, output: Wf, tags: Wf): WfQuery;
  /** Lean's CapDAG.Exec.queryConsuming : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
  queryConsuming(input: Wf, tags: Wf): WfQuery;
  /** Lean's CapDAG.Exec.queryGrade : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → CapDAG.Grade */
  queryGrade(q: WfQuery, c: WfCap): Grade;
  /** Lean's CapDAG.Exec.queryMayAdmit : CapDAG.Exec.WfQuery → CapDAG.Exec.WfCap → Bool */
  queryMayAdmit(q: WfQuery, c: WfCap): boolean;
  /** Lean's CapDAG.Exec.queryOfPattern : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery */
  queryOfPattern(p: WfCap): WfQuery;
  /** Lean's CapDAG.Exec.queryOfRequest : CapDAG.Exec.WfCap → CapDAG.Exec.WfQuery */
  queryOfRequest(r_: WfCap): WfQuery;
  /** Lean's CapDAG.Exec.queryProducing : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → CapDAG.Exec.WfQuery */
  queryProducing(output: Wf, tags: Wf): WfQuery;
  /** Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat */
  rankingKey(candidate: WfCap, request: WfCap): [bigint, bigint];
  /** Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap */
  select(candidates: Array<WfCap>, request: WfCap): L.Option<WfCap>;
  /** Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat */
  specificity(c: WfCap): bigint;
  /** Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf */
  make(scheme: string, tags: Array<[string, Constraint]>): L.Option<Wf>;
}

export interface LoadOptions {
  /** The program module (default: `program.wasm` next to this file). */
  module?: WebAssembly.Module | BufferSource;
  wasi?: L.Wasi;
}

export function load(options?: LoadOptions): Promise<CapdagFormal>;
