// Generated by lungo 1.75.3221 from Lean 4.34.1 for program capdagFormal. Do not edit.
import * as L from "lungo-ts";

/** Lean's CapDAG.Exec.WfCap. */
export interface WfCap {
  readonly input: Wf;
  readonly output: Wf;
  readonly other: Wf;
  readonly effect: Effect;
}
export function wfCapType(): L.Type<WfCap>;

/** Lean's CapDAG.Effect. */
export type Effect =
  | { readonly kind: "unspecified" }
  | { readonly kind: "declared" }
  | { readonly kind: "none" }
  | { readonly kind: "patch" }
;
export function effectType(): L.Type<Effect>;

/** Lean's TaggedUrn.Constraint. */
export type Constraint =
  | { readonly kind: "missing" }
  | { readonly kind: "unconstrained" }
  | { readonly kind: "optionalNot"; readonly value: string }
  | { readonly kind: "present" }
  | { readonly kind: "presentNot"; readonly value: string }
  | { readonly kind: "exact"; readonly value: string }
  | { readonly kind: "absent" }
;
export function constraintType(): L.Type<Constraint>;

/** Lean's TaggedUrn.Exec.Wf, held by handle: only the program's functions make and read its values. */
export class Wf extends L.Opaque {
  private constructor();
}
export function wfType(): L.Type<Wf>;

/** The layout fingerprint and descriptor of each type, by Lean name, for modules using them. */
export const leanTypes: {
  readonly [lean: string]: { readonly fingerprint: string; readonly type: (...args: L.Type<any>[]) => L.Type<any> };
};

/** The Lean program capdagFormal. */
export class CapdagFormal {
  private constructor();
  /** Lean's CapDAG.Exec.accepts : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  accepts(pattern: WfCap, request: WfCap): boolean;
  /** Lean's CapDAG.Exec.comparable : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  comparable(a: WfCap, b: WfCap): boolean;
  /** Lean's CapDAG.Exec.dispatch : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  dispatch(candidate: WfCap, request: WfCap): boolean;
  /** Lean's CapDAG.Exec.effectOk : CapDAG.Effect → CapDAG.Effect → Bool */
  effectOk(candidate: Effect, request: Effect): boolean;
  /** Lean's CapDAG.Exec.equivalent : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Bool */
  equivalent(a: WfCap, b: WfCap): boolean;
  /** Lean's CapDAG.Exec.rankingKey : CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Nat × Nat */
  rankingKey(candidate: WfCap, request: WfCap): [bigint, bigint];
  /** Lean's CapDAG.Exec.select : List CapDAG.Exec.WfCap → CapDAG.Exec.WfCap → Option CapDAG.Exec.WfCap */
  select(candidates: Array<WfCap>, request: WfCap): L.Option<WfCap>;
  /** Lean's CapDAG.Exec.specificity : CapDAG.Exec.WfCap → Nat */
  specificity(c: WfCap): bigint;
  /** Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf */
  make(scheme: string, tags: Array<[string, Constraint]>): L.Option<Wf>;
}

export interface LoadOptions {
  /** The program module (default: `program.wasm` next to this file). */
  module?: WebAssembly.Module | BufferSource;
  wasi?: L.Wasi;
}

export function load(options?: LoadOptions): Promise<CapdagFormal>;
